/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'MarkyMark' at '3/23/16 10:16 PM' with Gradle 2.2
 *
 * @author MarkyMark, @date 3/23/16 10:16 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
